seed_everything: 99
trainer:
  # logger: true
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
  checkpoint_callback: False
  num_nodes: 1
  num_processes: 2
  devices: null
  gpus: 1
  auto_select_gpus: true
  tpu_cores: null
  ipus: null
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: null
  min_epochs: null
  max_steps: 10
  min_steps: null
  max_time: 60
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 50
  accelerator: null
  sync_batchnorm: false
  precision: 16
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: false
  prepare_data_per_node: true
  plugins: null
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  callbacks:
  # - class_path: pytorch_lightning.callbacks.EarlyStopping
  #   init_args:
  #     patience: 5
  #     monitor: loss
  # - class_path: disentanglement_lib.methods.unsupervised.callbacks.Decomposition
  #   init_args:
  #     every_n_step: 200
model:
  img_shape:
  - 1
  - 64
  - 64
  
data:
  dataset: dsprites_tiny
  batch_size: 128
